### ISSUE TITLE
Updating the Methodology of the linear regression notebook

### ISSUE THREAD

**Issue by JarlineCardoso** [QuimicaUFPB/FindingPI#10]

**Comment by BorjaRuizReverter** [comment]
A introdução do notebook sobre regressão linear (FindingPIbyLinearRegression.ipynb) já está escrita @JarlineCardoso. Tenha melhor escrever a metodologia. 

Na metodologia, vc sabe, é para falar de:
1. Como foram tomadas as medidas (diretas) experimentais da superfície e a circunferência/diâmetro. Usa para isso as imagens que @Joabson-110 subiu.
2. A regressão linear, que é o método usado nesse notebook para encontrar o valor de PI.

Vou mandar @SandroRob mudar o nome dessas imagens, assim que, para que não dê conflito é melhor que vc trabalhe em outro branch. 

Vou então fechar mudar o nome deste issue para que fique claro de que trata e também abrir um branch novo para vc com seu nome para que vc trabalhe dai. 

Quando acabar suas mudanças nesse seu branch faça um "pull request". Dessa maneira eu reviso seu código e, se não houver conflito, faço uma fusão com o código principal (no branch main).

**Comment by JarlineCardoso** [comment]
oi, professor! tudo bem!
o senhor criou a filial? não encontrei por aqui... estou com dúvidas se é necessário adicionar as imagens na metodologia ou se há algum código que possa chamar elas na pasta onde já  estão inseridas.
também gostaria de comentar que nesse caso, vamos usar as medidas de circunferências e superfícies, pois lembra que o grupo 1 fez as medidas de circunferências deles tb, para que pudéssemos padronizar?

**Comment by BorjaRuizReverter** [comment]
Isso. É para usar as medidas da circunferência e da superfície. 

Filial? Quer dizer branch, né? Se for tem uma criada com seu nome!

No caso de adicionar as imagens, o melhor que vc as chame dentro do arquivo ipynb. Para isso usa esta notação em markdown:
```markdown
![nome_da_imagem](https://github.com/QuimicaUFPB/FindingPI/Imagens/nome_da_imagem)
```
Nesta conversa que a gente tem por aqui o Github usa internamente markdown, assim que da para aplicar um exemplo. Veja o código a seguir como exemplo:
![image](https://github.com/QuimicaUFPB/FindingPI/assets/35275075/76572792-891b-4976-a49d-5f90d725f7c5)

**Comment by JarlineCardoso** [comment]
Boa noite, professor! 
acabei de solicitar o pull a partir do meu Branch. Eu optei por não marcar as imagens pq eu tava escrevendo no celular, mas ao meu ver também dar certo assim pq as imagens so mostra os objetos utilizados e caso o leitor tenha interesse procuraria na pasta de imagens...
