### ISSUE TITLE
Submit a readme

### ISSUE THREAD

**Issue by BorjaRuizReverter** [QuimicaUFPB/FindingPI#2]
@JarlineCardoso, try to write a readme file (in markdown) describing what is the project FindingPI about. 

You can follow this guide to know how to use markdown if you will: https://www.markdownguide.org/basic-syntax/

**Comment by JarlineCardoso** [comment]
professor, veja se está bom ou preciso editar a descrição do projeto. Fiquei na dúvida se eu tiraria aquela  parte falando sobre o pi, mas deixei pra o senhor me dizer sua opinião.

**Comment by BorjaRuizReverter** [comment]
Está bem @JarlineCardoso. Vc pegou a ideia. Talvez falta acrescentar umas coisas, mas eu posso fazer.

**Comment by BorjaRuizReverter** [comment]
O problema está em que, agora que li com mais calma, o primeiro parágrafo trata da Organização que a gente montou aqui no Github (https://github.com/QuimicaUFPB) e o segundo do número PI, mas não do repositório. 

Vou então reabrir este issue para melhorar esse readme.

Tenta então fazer o seguinte:
1. Usa esse seu primeiro parágrafo e bota no readme de nossa Organização QuímicaUFPB. Mas tenha cuidado, pois o readme da Organização deve estar na pasta profile de repositório .github (https://github.com/QuimicaUFPB/.github/tree/main) e não fora dele como eu tinha feito de maneira errada. Sendo assim, pode apagar o readme que eu tinha feito ai.
2. Apaga esse segundo parágrafo e re-escreva algo diferente. Não é para falar de PI, se não do que estamos fazendo no repositório FindingPI, qual é o objetivo. Se quiser inspiração veja o readme de qualquer outro repositório. Aqui vai um exemplo: https://github.com/BorjaRuizReverter/LivroFisicaGeral

**Comment by JarlineCardoso** [comment]
professor, fiz o que o senhor pediu. Veja se ficou no local correto, por favor rsrs

**Comment by BorjaRuizReverter** [comment]
Muito bem. Vc colocou um readme certinho explicando sobre a nossa Organização... mas, deixaste o repositório FindingPI sem nada!

Tenta então escrever um readme explicando de que trata o repositório FindingPI. Só falta isso :monocle_face:

Se eu fosse vc apagaria o segundo parágrafo do readme que vc fez para a Organização e colocaria no repositório, acrescentando algumas coisas.

:rocket:

Simbora

**Comment by JarlineCardoso** [comment]
O leia-me do repositório FindingPI foi criado. Caso necessário alterar o texto pode me retornar, professor.
