### ISSUE TITLE
Insert x and y to build the polinomial fit (linear regression in our case)

### ISSUE THREAD

**Issue by BorjaRuizReverter** [QuimicaUFPB/FindingPI#5]
This code is not working, @IsabeliSouto, from this line on:
https://github.com/QuimicaUFPB/FindingPI/blob/93bfa013ebebe3d8fd08698c135194faa17b123f/Graficos/codigo_calculo_da_regress%C3%A3o_linear.py#L6

It seems that you missed the x and y coordinates (the experimental points) in the code. 

The experimental points are somewhere in another file. Please find them and fix this.

**Comment by IsabeliSouto** [comment]
feito
