### ISSUE TITLE
Add units to plot axis

### ISSUE THREAD

**Issue by BorjaRuizReverter** [QuimicaUFPB/FindingPI#6]
Units are missing in the plot axis, @HelayneRodrigues. Please add them. :rocket:

Here is the issue:
https://github.com/QuimicaUFPB/FindingPI/blob/93bfa013ebebe3d8fd08698c135194faa17b123f/Graficos/codigo_da_circuferencia_ao_quadrado_e_da_surperficie.py#L13C1-L14C25

**Comment by BorjaRuizReverter** [comment]
In case you have any doubt, @HelayneRodrigues, please follow the discussion regarding issue #9.

**Comment by HelayneRodrigues** [comment]
Boa tarde! @BorjaRuizReverter eu editei as unidades no código do gráfico da circunferência ao quadrado e da superfície. Por favor, confira se está certo.

**Comment by BorjaRuizReverter** [comment]
Está bem @HelayneRodrigues. Mas talvez vc poderia deixar igual como @IsabeliSouto fez, para que fique padronizado. Veja a discussão no issue #9 para entender.

**Comment by HelayneRodrigues** [comment]
Certo @BorjaRuizReverter. Acho que está padronizado agora.
