### ISSUE TITLE
Add units to plot axis

### ISSUE THREAD

**Issue by BorjaRuizReverter** [QuimicaUFPB/FindingPI#9]
Units are missing in the plot axis, @IsabeliSouto. Please add them. :wrench:

https://github.com/QuimicaUFPB/FindingPI/blob/d9e657596bbd9916d33f22e4e9ae0319156c248d/Graficos/codigo_calculo_da_regress%C3%A3o_linear.py#L21

**Comment by IsabeliSouto** [comment]
professor o código esta rodando normal aqui

**Comment by BorjaRuizReverter** [comment]
Sim, claro. O código está certo. É só para acrescentar as unidades nos eixos do gráfico e, com isso, gerar um gráfico padrão, no qual nos eixos sempre deve aparecer algo assim:
grandeza_física (unidades)

**Comment by IsabeliSouto** [comment]
no caso em vez de aparecer o nome superfície e circunferência ao quadrado, é para aparecer as unidade como grandeza_física s mm e grandeza_física c2 mm ficando neste estilo?

**Comment by BorjaRuizReverter** [comment]
Não. É para ficar assim:
S (mm²)
c² (mm²)

Mais tenha cuidado porque vai ter que fazer isso usando Latex. Veja [esse exemplo aqui](https://www.delftstack.com/howto/matplotlib/python-matplotlib-plot-superscript) para entender

**Comment by IsabeliSouto** [comment]
professor eu adicionei um titulo para o gráfico e adicionei  as unidades, veja se estar bom agora por favor
